yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Zero to Mastery Learn PyTorch for Deep Learning
site_url: https://www.learnpytorch.io
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/splendor1811/splendor1811.github.io
repo_name: mrdbourke/pytorch_deep_learning

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

